# ndarray 데이터 생성하기

In [1]:
import numpy as np

#### np.array 함수로 생성하기

In [3]:
x = np.array([1, 2, 3, 4])            # 1차원 행렬(벡터) 생성
print(x)

y = np.array([[2, 3, 4], [1, 2, 5]])  # 2차원 행렬 생성
print(y)

print(type(x))

[1 2 3 4]
[[2 3 4]
 [1 2 5]]
<class 'numpy.ndarray'>


#### np.arange 함수로 생성하기

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [5]:
np.arange(5, 101, 5)

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

#### np.ones, np.zeros로 생성하기

In [6]:
# 4행 5열의 모든 원소값이 1인 행렬 만들기
np.ones((4, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# 3행 4열이 2개인이고 모든 원소값이 1인 3차원 행렬 만들기
np.ones((2, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [7]:
# 2행 3열의 모든 원소값이 0인 행렬 만들기
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
# 3행 8열이 2개인이고 모든 원소값이 0인 3차원 행렬 만들기
np.zeros((2, 3, 8))

array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]]])

#### np.empty, np.full로 생성하기

In [9]:
# 어떤 값이든 상관 없고 초기화된 값을 갖고자 할 경우
np.empty((3, 4))

array([[6.76777499e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000]])

In [12]:
# 3행 4열의 모든 원소값이 7인 행렬 만들기
np.full((3, 4), 7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [13]:
np.full((3, 4, 2), 7)

array([[[7, 7],
        [7, 7],
        [7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7],
        [7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7],
        [7, 7],
        [7, 7]]])

#### np.eye로 생성하기
 - N차 단위행렬(대각선의 원소가 모두 1이며 나머지 원소는 모두 0인 정사각 행렬) 생성

In [14]:
# 5행 5열의 행렬의 대각선의 원소값만 1이고 나머지는 0인 행렬 만들기
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### np.linspace로 생성하기 (linear space)

In [15]:
# 1과 10을 포함해서 숫자 3개가 오도록 하는데 원소간의 차(spacing)가 동일 하도록 행렬 만들기
np.linspace(1, 10, 3)

array([ 1. ,  5.5, 10. ])

In [16]:
# 1과 10을 포함해서 숫자 4개가 오도록 하는데 원소간의 차(spacing)가 동일 하도록 행렬 만들기
np.linspace(1, 10, 4)

array([ 1.,  4.,  7., 10.])

In [17]:
# 1과 10을 포함해서 숫자 5개가 오도록 하는데 원소간의 차(spacing)가 동일 하도록 행렬 만들기
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

#### reshape 함수
 - ndarray 행렬을 다른 차원으로 바꾸는데 사용

In [21]:
x = np.arange(1, 16)  # 1차원 ndarray 생성
print(x)

print(x.shape)

y = x.reshape(3, 5)  # 1차원 이었던 ndarray를 2차원(3행 5열)의 ndarray 형태로 변경 함
print(y)
print(y.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
(15,)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
(3, 5)


In [22]:
x = np.arange(1, 16)  # 1차원 ndarray 생성
print(x)
print(type(x))
print(x.shape)

x.reshape(5, 3, 1)  # 1차원 이었던 ndarray를 3차원(3행 1열, 5개)의 ndarray 형태로 변경 함

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
<class 'numpy.ndarray'>
(15,)


array([[[ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])

In [25]:
x = np.arange(1, 16)  # 1차원 ndarray 생성
print(x)

x.shape

x.reshape(5, 4)  # 5*4 = 20 과 1~15까지의 숫자와 같이 않으면 에러 발생

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


ValueError: cannot reshape array of size 15 into shape (5,4)