# ndarray 데이터 생성하기(2)

In [2]:
import numpy as np

#### random 서브모듈의 함수를 사용해 ndarray 를 생성할 수 있습니다

#### rand 함수
 - 0, 1사이의 분포에서 랜덤한 ndarray 생성

In [3]:
# 2행 3열의 랜덤한 값을 생성, 랜덤한 값의 분포는 0과 1사이. 
np.random.rand(2, 3)

array([[0.44816805, 0.77864509, 0.44650843],
       [0.92703999, 0.72334612, 0.62059085]])

In [4]:
np.random.rand(2)  # 크기가 2인 1차원 벡터, 랜덤한 값의 분포는 0과 1사이.

array([0.92858073, 0.77178303])

In [5]:
np.random.rand(10)  # 크기가 10인 1차원 벡터, 랜덤한 값의 분포는 0과 1사이.

array([0.28010299, 0.32392038, 0.05508435, 0.29155356, 0.71227798,
       0.25205548, 0.67652491, 0.30683457, 0.42053306, 0.77362524])

In [6]:
np.random.rand(2, 5, 3)  # 5행 3열 이 2개인 3차원 행렬, 랜덤한 값의 분포는 0과 1사이.

array([[[0.2825851 , 0.65101302, 0.97728949],
        [0.08424059, 0.52003029, 0.03605832],
        [0.61915206, 0.96006205, 0.83250135],
        [0.38601963, 0.24301949, 0.9615222 ],
        [0.86349517, 0.51620714, 0.69047062]],

       [[0.96794228, 0.46762139, 0.87720669],
        [0.96464424, 0.89754389, 0.26207822],
        [0.27167747, 0.99966633, 0.02570107],
        [0.652647  , 0.07350171, 0.61169867],
        [0.15453445, 0.173977  , 0.00385404]]])

#### randn함수
 - n: normal distribution(정규분포)를 의미
 - 정규분포에서 샘플링된 랜덤 ndarray 생성

In [7]:
# 3행 4열로 정규분포에서 샘플링된 랜덤 값을 생성한다.
np.random.randn(3, 4)

array([[-0.80168305, -2.1799723 , -0.01907925, -0.47561737],
       [-0.12450499, -0.55465339, -0.42064375, -0.95182632],
       [-1.4483059 ,  1.37847543,  0.76904703,  1.09981268]])

In [8]:
# 4행 2열이 3개로 된 정규분포에서 샘플링된 랜덤 값을 생성한다.
np.random.randn(3, 4, 2)

array([[[-0.49235703,  1.78056777],
        [ 0.20553143, -2.5915142 ],
        [-0.19198621, -2.11704542],
        [-1.87171354,  2.67909791]],

       [[ 0.87952838,  1.13460545],
        [-0.29835489,  0.7275058 ],
        [ 0.96924693,  1.27533443],
        [ 0.4829333 , -0.11238582]],

       [[ 0.50393745, -0.5327424 ],
        [-0.28538809, -0.22484349],
        [ 1.28218506,  0.28632242],
        [ 0.7838584 , -1.3914782 ]]])

In [9]:
# 1차원 벡터 ,정규분포에서 샘플링된 랜덤 값을 생성한다.
np.random.randn(5)

array([-0.87140121, -0.7475477 ,  2.75307209, -0.0213475 ,  0.38322589])

#### randint 함수
 - 특정 범위에 속해있는 정수 중에서 랜덤하게 샘플링

In [10]:
# 정수 1 ~ 99 사이에서 3행 5열로 랜덤하게 샘플링해서 생성하라
np.random.randint(1, 100, size=(3, 5))

array([[88,  9, 44, 68, 38],
       [90, 86, 35, 10, 87],
       [86, 50, 92, 48, 61]])

In [11]:
# 정수 1 ~ 99 사이에서 3행 5열이 2개인 3차원 행렬을 랜덤하게 샘플링해서 생성하라
np.random.randint(1, 100, size=(2, 3, 5))

array([[[55, 73, 53, 66, 10],
        [96, 66, 42, 23, 66],
        [44, 47, 19, 69, 17]],

       [[12,  8, 22, 66, 61],
        [68, 82, 32, 91, 13],
        [25, 32, 16,  5, 36]]])

In [12]:
# 정수 1 ~ 99 사이에서 크기가 5인 1차원 행렬을 랜덤하게 샘플링해서 생성하라
np.random.randint(1, 100, size=(5))

array([71, 26, 36, 63, 11])

#### seed 함수
 - 누가, 언제하든지 똑같은 난수 생성을 원한다면 시드(seed) 번호를 설정해 주면 됨
 - 시드(seed) 번호는 0과 같거나 큰 임의의 정수를 넣어 주면 됨
 - 설정한 시드번호를 다시 실행한 후 다시 난수를 발행하면 예전에 발생했던 난수 순서로 동일하게 발행됨으로 코드의 결과를 그대로 재현 할 수 있음

In [13]:
np.random.seed(0) # 시드 설정

In [14]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [15]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [16]:
np.random.rand(10)

array([0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215,
       0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443])

In [17]:
np.random.seed(0) # 시드 재설정

In [18]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [19]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [20]:
np.random.rand(10)

array([0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215,
       0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443])

#### choice 함수
 - 주어진 벡터 ndarray로부터 랜덤하게 샘플링
 - 정수가 주어진 경우에는 np.arange(해당숫자)로 간주
 - replace=False 이면 중복을 허용하지 않음

In [21]:
# 0~99 로 구성된 1차원 벡터로부터 3행 4열의 행렬에 랜덤하게 샘플링하여 가져오라
np.random.choice(100, size=(3, 4))

array([[32, 65,  9, 57],
       [32, 31, 74, 23],
       [35, 75, 55, 28]])

In [22]:
x = np.array([1, 2, 3, 1.5, 2.6, 4.9])
np.random.choice(x, size=(2,2))  # 주어진 x에서 2행 2열로 랜덤하게 샘플링하여 가져옴, 중복을 허용함

array([[3. , 1. ],
       [1. , 2.6]])

In [23]:
x = np.array([1, 2, 3, 1.5, 2.6, 4.9])
np.random.choice(x, size=(2,2), replace=False)  # 주어진 x에서 2행 2열로 랜덤하게 샘플링하여 가져옴, 중복을 허용하지 않음

array([[1.5, 3. ],
       [2. , 2.6]])

#### 확률분포 함수
 - uniform 함수(균등분포에서 램덤하게 샘플링)
 - normal 함수(정규분포에서 램덤하게 샘플링)

In [24]:
# uniform 분포로 1,0 ~ 3.0 까지 랜덤하게 4행 5열로 생성
np.random.uniform(1.0, 3.0, size=(4, 5))

array([[2.80519695, 1.89989998, 2.22612692, 2.80469717, 1.1985607 ],
       [2.93961814, 2.30628007, 1.34181917, 1.71630433, 2.50137228],
       [2.21566134, 1.65009446, 1.07685085, 2.26854812, 2.91789854],
       [2.30558063, 2.27011775, 2.99059914, 2.16370066, 1.82873718]])

In [25]:
# normal(정규) 분포로 랜덤하게 3행 4열로 생성
np.random.normal(size=(3, 4))

array([[ 2.29977152, -0.47113526,  1.26271548, -1.17051545],
       [ 1.0657892 , -0.69993739,  0.14407911,  0.3985421 ],
       [ 0.02686925,  1.05583713, -0.07318342, -0.66572066]])

In [26]:
np.random.randn(3, 4)  # 위 함수와 동일하게 작동됨

array([[-0.04411241, -0.36326702, -0.01234481,  0.04212149],
       [ 1.95929589, -0.1984257 ,  0.33053441, -1.43582841],
       [ 0.02752832,  1.12060466, -0.22403878, -0.42018339]])