# ndarray 데이터 생성하기(2)

In [1]:
import numpy as np

#### random 서브모듈의 함수를 사용해 ndarray 를 생성할 수 있습니다

#### rand 함수
 - 0, 1사이의 분포에서 랜덤한 ndarray 생성

In [4]:
# 2행 3열의 랜덤한 값을 생성, 랜덤한 값의 분포는 0과 1사이.
np.random.rand(2, 3)

array([[0.08394797, 0.61495885, 0.67409363],
       [0.14757392, 0.96242675, 0.21358068]])

In [5]:
np.random.rand(2)  # 크기가 2인 1차원 벡터, 랜덤한 값의 분포는 0과 1사이.

array([0.6557417 , 0.95234485])

In [6]:
np.random.rand(10)  # 크기가 10인 1차원 벡터, 랜덤한 값의 분포는 0과 1사이.

array([0.79090152, 0.97864004, 0.69320198, 0.30916119, 0.34827184,
       0.46647081, 0.97203601, 0.21105142, 0.31230269, 0.71781703])

In [8]:
np.random.rand(2, 5, 3)  # 5행 3열 이 2개인 3차원 행렬, 랜덤한 값의 분포는 0과 1사이.

array([[[0.45563394, 0.5120981 , 0.25476355],
        [0.51497263, 0.98515693, 0.8410353 ],
        [0.83100128, 0.31272377, 0.10034783],
        [0.39135554, 0.49709098, 0.09870215],
        [0.0345411 , 0.16827495, 0.22652441]],

       [[0.71018704, 0.42220278, 0.71957994],
        [0.9439637 , 0.83610696, 0.40086405],
        [0.19823433, 0.68013774, 0.56221165],
        [0.02155401, 0.84905797, 0.97317261],
        [0.08068304, 0.36777573, 0.42308754]]])

#### randn함수
 - n: normal distribution(정규분포)를 의미
 - 정규분포에서 샘플링된 랜덤 ndarray 생성

In [ ]:
# 3행 4열로 정규분포에서 샘플링된 랜덤 값을 생성한다.
np.random.randn(3, 4)

array([[ 1.52190837, -1.39471511,  1.25806257, -0.83612636],
       [ 1.64182211,  2.35778917, -0.36303697, -0.74503516],
       [-0.54846207, -0.19017871, -1.63816602,  0.74124083]])

In [10]:
# 4행 2열이 3개로 된 정규분포에서 샘플링된 랜덤 값을 생성한다.
np.random.randn(3, 4, 2)

array([[[-0.04352036, -0.80282011],
        [ 0.44508032,  1.47238166],
        [ 0.26678081, -0.48476886],
        [-0.75668331, -0.73123001]],

       [[-0.30029783,  1.71981965],
        [ 0.37882806, -1.29773142],
        [ 0.70539021,  0.22719904],
        [-1.34124117, -0.84462137]],

       [[-0.32060046, -0.71655396],
        [-0.37318054, -0.05600092],
        [-0.27436804, -0.93128358],
        [ 0.42564246, -0.36201825]]])

In [11]:
# 1차원 벡터 ,정규분포에서 샘플링된 랜덤 값을 생성한다.
np.random.randn(5)

array([-0.06674761, -1.0176595 , -0.06178262, -1.78773317, -0.05782862])

#### randint 함수
 - 특정 범위에 속해있는 정수 중에서 랜덤하게 샘플링

In [12]:
# 정수 1 ~ 99 사이에서 3행 5열로 랜덤하게 샘플링해서 생성하라
np.random.randint(1, 100, size=(3, 5))

array([[52, 63, 53, 31, 24],
       [13, 46, 69,  9, 96],
       [89, 38, 16,  8, 64]])

In [13]:
# 정수 1 ~ 99 사이에서 3행 5열이 2개인 3차원 행렬을 랜덤하게 샘플링해서 생성하라
np.random.randint(1, 100, size=(2, 3, 5))

array([[[95, 71, 44, 99, 37],
        [24, 45, 52, 84, 10],
        [89, 26, 60, 26, 60]],

       [[97, 85,  3, 96, 84],
        [50, 50, 46, 73, 29],
        [ 1, 48, 54, 28, 90]]])

In [14]:
# 정수 1 ~ 99 사이에서 크기가 5인 1차원 행렬을 랜덤하게 샘플링해서 생성하라
np.random.randint(1, 100, size=(5))

array([ 4, 46, 36, 39, 21])

#### seed 함수
 - 누가, 언제하든지 똑같은 난수 생성을 원한다면 시드(seed) 번호를 설정해 주면 됨
 - 시드(seed) 번호는 0과 같거나 큰 임의의 정수를 넣어 주면 됨
 - 설정한 시드번호를 다시 실행한 후 다시 난수를 발행하면 예전에 발생했던 난수 순서로 동일하게 발행됨으로 코드의 결과를 그대로 재현 할 수 있음

In [15]:
np.random.seed(2024) # 시드 설정

In [16]:
np.random.rand(5)

array([0.58801452, 0.69910875, 0.18815196, 0.04380856, 0.20501895])

In [17]:
np.random.rand(10)

array([0.10606287, 0.72724014, 0.67940052, 0.4738457 , 0.44829582,
       0.01910695, 0.75259834, 0.60244854, 0.96177758, 0.66436865])

In [18]:
np.random.rand(10)

array([0.60662962, 0.44915131, 0.22535416, 0.6701743 , 0.73576659,
       0.25799564, 0.09554215, 0.96090974, 0.25176729, 0.28216512])

In [19]:
np.random.seed(2024) # 시드 재설정

In [20]:
np.random.rand(5)

array([0.58801452, 0.69910875, 0.18815196, 0.04380856, 0.20501895])

In [21]:
np.random.rand(10)

array([0.10606287, 0.72724014, 0.67940052, 0.4738457 , 0.44829582,
       0.01910695, 0.75259834, 0.60244854, 0.96177758, 0.66436865])

In [22]:
np.random.rand(10)

array([0.60662962, 0.44915131, 0.22535416, 0.6701743 , 0.73576659,
       0.25799564, 0.09554215, 0.96090974, 0.25176729, 0.28216512])

#### choice 함수
 - 주어진 벡터 ndarray로부터 랜덤하게 샘플링
 - 정수가 주어진 경우에는 np.arange(해당숫자)로 간주
 - replace=False 이면 중복을 허용하지 않음

In [23]:
# 0~99 로 구성된 1차원 벡터로부터 3행 4열의 행렬에 랜덤하게 샘플링하여 가져오라
np.random.choice(100, size=(3, 4))

array([[57, 86, 54, 20],
       [ 8, 18, 97, 90],
       [74,  7, 48, 53]])

In [24]:
x = np.array([1, 2, 3, 1.5, 2.6, 4.9])
np.random.choice(x, size=(2,2))  # 주어진 x에서 2행 2열로 랜덤하게 샘플링하여 가져옴, 중복을 허용함

array([[4.9, 1. ],
       [1. , 1.5]])

In [25]:
x = np.array([1, 2, 3, 1.5, 2.6, 4.9])
np.random.choice(x, size=(2,2), replace=False)  # 주어진 x에서 2행 2열로 랜덤하게 샘플링하여 가져옴, 중복을 허용하지 않음

array([[3. , 2. ],
       [1. , 2.6]])

#### 확률분포 함수
 - uniform 함수(균등분포에서 램덤하게 샘플링)
 - normal 함수(정규분포에서 램덤하게 샘플링)

In [26]:
# uniform 분포로 1,0 ~ 3.0 까지 랜덤하게 4행 5열로 생성
np.random.uniform(1.0, 3.0, size=(4, 5))

array([[1.08021258, 2.48858659, 1.71155713, 1.28694297, 2.21812513],
       [1.08803208, 2.83930843, 2.82907344, 2.71208354, 2.91715517],
       [2.44210452, 1.3010006 , 2.88520653, 2.14620958, 1.14722984],
       [1.59044863, 2.99656303, 2.73534135, 1.37563209, 2.77184343]])

In [27]:
# normal(정규) 분포로 랜덤하게 3행 4열로 생성
np.random.normal(size=(3, 4))

array([[-0.50751739,  0.22555803, -0.36996176,  0.18063043],
       [-0.64847861, -0.44893288, -0.27106748, -0.91858758],
       [-2.16268933, -0.39674428, -0.99032874,  0.18720857]])

In [28]:
np.random.randn(3, 4)  # 위 함수와 동일하게 작동됨

array([[-0.40899007,  0.27233448, -0.02031703, -0.08830022],
       [-2.48876591,  0.3103731 , -0.52346094, -1.31325829],
       [ 0.73839058, -0.30456368, -0.51018119, -0.78667537]])