# ndarray 데이터 형태 바꾸기

In [1]:
import numpy as np

#### ravel 멤버함수와 np.ravel 함수
  - ndarray를 1차원 행렬(벡터)로 변경
  - np.ravel의 'order' 파라미터
    - order='C' : row(행) 기준으로 펴줍니다
    - order='F' : column(열) 기준으로 펴줍니다

In [2]:
x = np.arange(15).reshape(3, 5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [4]:
x.ravel()  # n차원의 배열을 1차원 벡터로 만들어 준다.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
temp = x.ravel()
print(temp)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [7]:
temp[0] = 100   # ravel 은 원본 값을 그대로 가져오기 때문에 원본 그 자체가 수정이 됨
print(temp)
print(x)

[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14]
[[100   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]]


In [8]:
np.ravel(x)

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14])

In [ ]:
np.ravel(x, order='C') # order = 'C' 이면 행 기준으로 펴짐

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14])

In [ ]:
np.ravel(x, order='F') # order = 'F 이면 열 기준으로 펴짐

array([100,   5,  10,   1,   6,  11,   2,   7,  12,   3,   8,  13,   4,
         9,  14])

#### flatten 멤버함수
 - ndarray를 1차원 행렬(벡터)로 변경
 - ravel과의 다른점: 원본은 그대로 두고 복사(copy)본을 생성하여 shape을 변경함
 - 'order' 파라미터
   - order='C' : row(행) 기준으로 펴줍니다.
   - order='F : column(열) 기준으로 펴줍니다.

In [9]:
y = np.arange(15).reshape(3, 5)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [10]:
y.flatten()  # n차원의 배열을 1차원 벡터로 만들어 준다.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
t2 = y.flatten()
print(t2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [12]:
t2[0] = 100  # flatten 을 사용하면 원본이 아닌 복사본을 사용하기 때문에 복사본이 수정되더라도 원본은 그대로 유지 됨
print(t2)
print(y)

[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [13]:
t2 = y.flatten(order='C') # order = 'C' 이면 행 기준으로 펴짐
print(t2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [14]:
t2 = y.flatten(order='F') # order = 'F 이면 열 기준으로 펴짐
print(t2)

[ 0  5 10  1  6 11  2  7 12  3  8 13  4  9 14]


#### reshape 함수
 - ndarray의 shape을 다른 차원으로 변경
 - 원본 원소의 개수와 변경하려는 차원의 원소의 개수는 같아야 함

In [15]:
x = np.arange(36)
print(x)
print(x.shape) # x의 모양 출력
print(x.ndim)  # x의 차원수 출력

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]
(36,)
1


In [16]:
x.reshape(6, 6)  # 6행 6열로 생성

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [17]:
x.reshape(6, -1)  # 6행이면서 열을 자동계산하여 행렬 생성, 하나(행)가 결정되면 나머지(열)는 자동계산(-1 로 적어줌)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [18]:
x.reshape(-1, 6)  #6열이면서 행은 자동계산하여 행렬 생성, 하나(열)가 결정되면 나머지(행)는 자동계산(-1 로 적어줌)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [19]:
y = x.reshape(6, 6)
print(y.shape) # y의 모양 출력
print(y.ndim)  # y의 차원수 출력

(6, 6)
2


In [ ]:
k = x.reshape(3, 3, 4)  # x.reshape(3, 3, -1), x.reshape(3, -1, 4), x.reshape(-1, 3, 4) 로 해도 자동계산하여 동일한 결과를 가져옴
print(k)
print(k.shape)
print(k.ndim)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]
(3, 3, 4)
3
