# numpy 기본함수

In [1]:
import numpy as np

#### numpy documentation
 - [numpy 공식 문서 링크](https://www.numpy.org/devdocs/reference/)
 - numpy에서 제공되는 함수 등에 대한 문서

#### 연산 함수
 - add, substract, multiply, divide
 - ndarray 끼리의 연산은 둘 다 shape이 같아야 함

In [2]:
x = np.arange(15).reshape(3, 5)
y = np.random.rand(15).reshape(3, 5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.68639804 0.65463909 0.60217544 0.00356057 0.89782054]
 [0.11399745 0.62696048 0.08201844 0.25344996 0.43077821]
 [0.65912134 0.57323302 0.84599387 0.73516595 0.60974032]]


In [3]:
print(x.shape, y.shape)

(3, 5) (3, 5)


In [4]:
np.add(x, y)  # 인덱스가 같은 원소끼리 더한다.

array([[ 0.68639804,  1.65463909,  2.60217544,  3.00356057,  4.89782054],
       [ 5.11399745,  6.62696048,  7.08201844,  8.25344996,  9.43077821],
       [10.65912134, 11.57323302, 12.84599387, 13.73516595, 14.60974032]])

In [5]:
np.divide(x, y)

array([[  0.        ,   1.52755925,   3.32129124, 842.56230808,
          4.45523334],
       [ 43.86063002,   9.56998113,  85.34666562,  31.56441639,
         20.8924216 ],
       [ 15.17171331,  19.18940407,  14.18449987,  17.6830823 ,
         22.96059415]])

In [6]:
x + y  # 바로 연산자 이용 가능, 단 ndarray 끼리의 연산은 그 두개의 ndarray가 shape 이 같아야 한다.

array([[ 0.68639804,  1.65463909,  2.60217544,  3.00356057,  4.89782054],
       [ 5.11399745,  6.62696048,  7.08201844,  8.25344996,  9.43077821],
       [10.65912134, 11.57323302, 12.84599387, 13.73516595, 14.60974032]])

In [7]:
x * y # 바로 연산자 이용 가능, 단 ndarray 끼리의 연산은 그 두개의 ndarray가 shape 이 같아야 한다.

array([[ 0.        ,  0.65463909,  1.20435087,  0.0106817 ,  3.59128216],
       [ 0.56998725,  3.7617629 ,  0.57412905,  2.02759966,  3.8770039 ],
       [ 6.59121339,  6.30556319, 10.15192649,  9.55715735,  8.53636447]])

#### 통계 함수
 - 평균, 분산, 중앙값, 최대값, 최소값 등 통계 관련된 함수

In [8]:
print(y)

[[0.68639804 0.65463909 0.60217544 0.00356057 0.89782054]
 [0.11399745 0.62696048 0.08201844 0.25344996 0.43077821]
 [0.65912134 0.57323302 0.84599387 0.73516595 0.60974032]]


In [9]:
np.mean(y)  # 평균 계산

0.5183368476899197

In [10]:
y.mean()  # 평균 계산

0.5183368476899197

In [11]:
np.max(y) # 최대값

0.8978205394940286

In [12]:
np.argmax(y) # 최대값의 index

4

In [13]:
np.var(y), np.median(y), np.std(y)  # 분산, 중앙값, 표준편차

(0.07279409924954892, 0.6097403189807535, 0.2698038162249543)

#### 집계함수
 - 합계(sum), 누적합계(cumsum) 등

In [14]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [15]:
np.sum(x)  # 모든 원소의 합계

105

In [16]:
np.cumsum(x) # n번째 원소(누적합) = n-1번째 원소까지의 누적합 + n번째 원소

array([  0,   1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,
        91, 105])

#### any, all 함수
 - any: 특정 조건을 만족하는 것이 하나라도 있으면 True, 아니면 False
 - all: 모든 원소가 특정 조건을 만족한다면 True, 아니면 False

In [17]:
z = np.random.randn(10)
print(z)

[-0.18680331  1.542652   -0.02744817  0.65453719 -0.40870094  0.95235532
  0.40706607  0.07713927  0.47314166 -0.6980813 ]


In [18]:
z > 0  # 각 원소를 Boolean array 로 저장

array([False,  True, False,  True, False,  True,  True,  True,  True,
       False])

In [19]:
np.any(z > 0)  # 조건이 하나라도 참이면 True

True

In [20]:
np.all(z > 0)  # 모두 참이여야만 True

False

In [21]:
np.all(z != 0)  # 모두 참이여야만 True

True

#### where 함수
 - 조건에 따라 행렬 각 원소의 값을 선택하여 설정할 수 있음
 - np.where(조건, 참일때 선택값, 거짓일때 선택값)

In [22]:
z = np.random.randn(10)
print(z)

[-0.15737416  0.82293524  0.05798107 -1.45522958  0.77373841  1.69724684
  0.58390418  0.79091295  0.94784077  2.07572091]


In [ ]:
# np.where(조건, 참값, 거짓값)
np.where(z > 0, z, 0)  # 조건을 만족하면 z 값을 그대로 쓰고, 거짓이면 0으로 대치함

array([0.        , 0.        , 2.84874199, 0.6380972 , 0.        ,
       1.25205107, 0.        , 0.        , 0.        , 1.13517431])