# broadcasting

In [1]:
import numpy as np

#### 브로드캐스팅
  - 연산되는 두 행렬의 shape이 다른 경우 shape이 작은 행렬이 늘어나서(stretch) shape을 맞춰 연산을 진행
  - shape이 작은 행렬이 모두 broadcasting 되는 것은 아니며 broadcasting 규칙에 의해 broadcasting 여부 결정
  - broadcasting 규칙
     + 2차원 행렬과 1차원 행렬(벡터)간의 연산
         * 두 행렬의 뒷차원 shape 이 같으면 broadcasting 가능
     + 두 2차원 행렬 간의 연산
         * 두 행렬의 뒷차원 shape 이 같으며, 두 행렬 중 어느 하나가 행이 하나만 있는 행렬이라면 broadcasting 가능
  
    


![브로드캐스팅 예](https://www.tutorialspoint.com/numpy/images/array.jpg)
    - 출처: https://www.tutorialspoint.com/numpy/images/array.jpg

* shape이 같은 행렬 연산

In [2]:
x = np.arange(15).reshape(3, 5)
y = np.random.rand(15).reshape(3, 5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.69948481 0.48993668 0.94917923 0.30764271 0.0549725 ]
 [0.86199746 0.51997156 0.66222824 0.34383952 0.06691636]
 [0.35323652 0.67177021 0.43749561 0.02369355 0.4870901 ]]


In [ ]:
x + y  # 각 index 가 매칭되는 값끼리 더해서 동일한 크기(3, 5)의 행렬이 생성

array([[ 0.13495753,  1.0813142 ,  2.84977575,  3.44866155,  4.22822189],
       [ 5.71378474,  6.78668156,  7.20301704,  8.3050053 ,  9.093414  ],
       [10.20997653, 11.55163848, 12.96509506, 13.30887423, 14.84060497]])

* scalar(상수)와 행렬의 연산

In [3]:
x + 2  # 모든 원소에 2가 더해짐

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [4]:
x * 2  # 모든 원소 2를 곱합

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [5]:
x ** 2  # 모든 원소에 제곱을 함

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]])

In [6]:
x % 2 == 0  # 모든 원소에 Boolean 를 적용 함

array([[ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True]])

* shape이 다른 행렬 연산

In [ ]:
a = np.arange(12).reshape(4, 3)
b = np.arange(100, 103)
c = np.arange(1000, 1004)
d = b.reshape(1, 3)

print(a)
print(b)
print(c)
print(d)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[100 101 102]
[1000 1001 1002 1003]
[[100 101 102]]


In [ ]:
print(a.shape) # (4, 3)
print(b.shape) # (3,) : 벡터 ==>  (4, 3)의 뒷 차원 즉, 3 과 3이 비교하여 같기 때문에 연산이 가능
print(c.shape) # (4,) : 벡터 ==>  (4, 3)의 뒷 차원 즉, 3 과 4가 비교하여 같지 않기 때문에 연산이 불가능
print(d.shape) # (1, 3) : 행렬 ==>  (4, 3)의 뒷 차원 3 과 (1, 3)의 뒷 차원 3이 비교하여 같고 앞에 차원이 1이기 때문에 연산이 가능

(4, 3)
(3,)
(4,)
(1, 3)


In [ ]:
a + b  # 연산가능

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [ ]:
a + c  # 연산불가

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [ ]:
a + d  # 연산가능

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])